configMapGenerator:
- files:
  - application.yml
  name: troubleshooting-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ceappacr.azurecr.io/troubleshooting
  newTag: "202410100615"
- name: cepgbaseacr.azurecr.io/troubleshooting
  newTag: "202410090852"
- name: cepgstapacr.azurecr.io/troubleshooting
  newTag: "202410100642"
